<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.mines.address.domain.service.PersonServiceTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2025-02-03T11:02:25" hostname="fadia-HP-Envy-Laptop-17-cw0xxx" time="1.843">
  <properties/>
  <testcase name="shouldSaveAPerson()" classname="org.mines.address.domain.service.PersonServiceTest" time="1.808"/>
  <testcase name="shouldThrowExceptionWhenPersonAlreadyExists()" classname="org.mines.address.domain.service.PersonServiceTest" time="0.028"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[WARNING: A Java agent has been loaded dynamically (/home/fadia/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.14.11/f9cb566608fbac6bc7bf54901a7aa11543a989ee/byte-buddy-agent-1.14.11.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
]]></system-err>
</testsuite>
